### ISSUE TITLE
Hello, when I trained an aesthetic model using the default configuration on 8 A800 cards, I found that the training process got stuck after completing one epoch, but it worked fine when using a single A800 card. May I ask what could be the cause of this situation?

### ISSUE THREAD

**Issue by cjt222** [kvablack/ddpo-pytorch#13]
Hello, when I trained an aesthetic model using the default configuration on 8 A800 cards, I found that the training process got stuck after completing one epoch, but it worked fine when using a single A800 card. May I ask what could be the cause of this situation?

**Comment by mihirp1998** [comment]
same issue after 2 epochs, the model seems to get stuck at waiting for rewards..

Please let me know if you have a soln @cjt222 or @kvablack ?

**Comment by cjt222** [comment]
Currently, there is no solution, and I am currently using a single A800 card for training.

**Comment by mihirp1998** [comment]
is this problem just for the aesthetic model or for others too?

**Comment by cjt222** [comment]
Not only the aesthetic model, but also other tasks are facing the same issue.

**Comment by desaixie** [comment]
This is caused by `accelerator.save_state()` at this [line](https://github.com/kvablack/ddpo-pytorch/blob/main/scripts/train.py#L507). This bug appeared after a recent [commit ](https://github.com/kvablack/ddpo-pytorch/commit/5955244f37d74295fa9959c3bef999b1ef1cf7b8). It was meant to solve a [bug](https://github.com/huggingface/diffusers/issues/4046) in `diffuers` as discussed in #10 . A temporary solution is to simply commenting out this line. A complete solution is to follow [this](https://github.com/huggingface/diffusers/blob/main/examples/text_to_image/train_text_to_image_lora_sdxl.py) or [this](https://github.com/williamberman/diffusers/blob/main/examples/dreambooth/train_dreambooth_lora.py) training script, use their code that deals with LoRA to replace those in the current DDPO training script.

**Comment by kvablack** [comment]
Thanks so much @desaixie for investigating this! Strangely enough, it works on my machine.

If you have a working version of the code, would you mind opening a pull request? To be honest, I never really wrapped my head around the accelerate save/load API.

**Comment by cjt222** [comment]
After testing, it is confirmed that multi-card training is feasible when the acceleration is reduced to 0.17 @kvablack @mihirp1998 @desaixie

**Comment by mihirp1998** [comment]
@cjt222  what do u mean by acceleration reduced to 0.17?

**Comment by cjt222** [comment]
pip install accelerate==0.17

**Comment by kvablack** [comment]
Thanks everyone, I added `accelerate==0.17` to `setup.py`.
