### ISSUE TITLE
Support for other schedulers

### ISSUE THREAD

**Issue by desaixie** [kvablack/ddpo-pytorch#14]
This code currently only supports DDIM. In the recently released [SD-XL](https://huggingface.co/docs/diffusers/api/pipelines/stable_diffusion/stable_diffusion_xl), the default scheduler is [EulerDiscrete](https://huggingface.co/docs/diffusers/v0.20.0/en/api/schedulers/euler#diffusers.EulerDiscreteScheduler). From the [paper](https://arxiv.org/abs/2206.00364) and the [code](https://github.com/huggingface/diffusers/blob/v0.20.0/src/diffusers/schedulers/scheduling_euler_discrete.py#L309), it seems that the `prev_sample` is no longer sampled from a Gaussian distribution but a ODE solution instead (correct me if I am wrong here). How to calculate the log_prob of `prev_sample` given the `noise_pred` in this case?

**Comment by kvablack** [comment]
I'm not very familiar with other schedulers, which is why we stuck with DDIM. I'd imagine it's possible to compute a policy gradient with respect to 2nd order samplers (such as EulerDiscrete), but it's going to require some in-depth knowledge of the math (which I frankly don't have). Sounds like a great direction for future work!
