### ISSUE TITLE
fp16 only if using lora?

### ISSUE THREAD

**Issue by GiilDe** [kvablack/ddpo-pytorch#8]
This may be a noob question, but can you explain this line where you transfer the model to fp16 or bfp16 only if using lora?
https://github.com/kvablack/ddpo-pytorch/blob/173b2bb6e0e3b2feb7587c98bb54f63b1d3867d5/scripts/train.py#L117C22-L117C22

**Comment by kvablack** [comment]
Sure thing! You don't want training weights to be low-precision, or it can cause instability. Therefore, when not using LoRA, we want to keep the UNet params in full float32. If we're using LoRA, we're not training the UNet params, so we can cast them to low precision. That's why the variable is called `inference_dtype`.

**Comment by GiilDe** [comment]
I see, thanks!
